server:
  port: 1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/item_mania?serverTimezone=Asia/Seoul&useSSL=false
    username: bitai
    password: 456123
    driver-class-name: com.mysql.cj.jdbc.Driver